#Desarrollador:

kind:           Deployment
apiVersion:     apps/v1

metadata:
    name:       deployment-wordpress
    labels:
        app:    wordpress

spec: 
    replicas:   1
    
    selector:
        matchLabels:
            app:        wordpress
    
    template:
        metadata:
            name:       pod-wordpress
            labels:
                app:    wordpress
        
        spec: 
            volumes:
                -   name:   persistencia
                    persistentVolumeClaim:
                        claimName: mi-peticion-wordpress
            containers:
                -   name:   mi-contenedor
                    image:  wordpress:latest
                    volumeMounts:
                        -   name:   persistencia
                            mountPath: /var/www/html
                    ports:
                        - containerPort: 80
                    env:
                        -   name:   WORDPRESS_DB_HOST
                            value:  db
                                    
                        -   name:   WORDPRESS_DB_NAME
                            valueFrom:  
                                configMapKeyRef:
                                    name:   configuracion-mariadb
                                    key:    BaseDatos_nombre
                                    
                        -   name:   WORDPRESS_DB_USER
                            valueFrom:  
                                configMapKeyRef:
                                    name:   configuracion-mariadb
                                    key:    Usuario_nombre
                                    
                        -   name:   WORDPRESS_DB_PASSWORD
                            valueFrom:  
                                secretKeyRef:
                                    name:   configuracion-mariadb
                                    key:    Usuario_contrasena

---
kind:           Service
apiVersion:     v1

metadata:
    name:       wp

spec: 
    type:       NodePort
    ports:  
               -    port: 80
                    targetPort: 80
                    nodePort: 30080
    selector:
        app:    wordpress