#ulimit -n 131072
#ulimit -u 8192
#echo "elasticsearch  -  nofile  65535" | sudo tee -a /etc/security/limits.conf
#sudo sysctl -w fs.file-max=131072
#sudo sysctl -w vm.max_map_count=262144
#echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
#echo "fs.file-max=131072" | sudo tee -a /etc/sysctl.conf
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       test-elasticsearch

data:
    ready.sh: |
        #!/bin/bash
        echo OK
        # curl -s http://localhost:9200 | grep -q 'for search'
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       datos-aplicacion

data:
    cluster.name: micluster
    cluster.initial_master_nodes: es-0,es-1,es-2        # TODO: RUINA !!!!
    discovery.seed_hosts: es-0.elasticsearch,es-1.elasticsearch,es-2.elasticsearch # RUINA !!!
    bootstrap.memory_lock: "true"
    xpack.security.enabled: "false"
    ES_JAVA_OPTS: "-Xms1250m -Xmx1250m"

---
kind:           StatefulSet
apiVersion:     apps/v1

metadata:
    name:       es
    labels:
        app:    elasticsearch

spec: 
    replicas:   3
        # es-0
        # es-1
        # es-2
    serviceName:    elasticsearch
        # es-0.elasticsearch
        # es-1.elasticsearch
        # es-2.elasticsearch
    selector:
        matchLabels:
            app:        elasticsearch
    
    volumeClaimTemplates:
        -   metadata:
                name:   datos-aplicacion
            
            spec:
                resources:
                    requests:
                        storage:    1Gi
                storageClassName:   redundante
                accessModes:
                    - ReadWriteMany
    
    template:
        metadata:
            labels:
                app:    elasticsearch
        
        spec:
            volumes:

                -   name:       test-elasticsearch
                    configMap:
                        name:   test-elasticsearch
                        defaultMode: 0777

            containers:
                -   name:   mi-contenedor
                    image:  docker.elastic.co/elasticsearch/elasticsearch:8.3.2
                    securityContext:
                        privileged: true
                        capabilities:
                            add:
                                - IPC_LOCK

                    imagePullPolicy: IfNotPresent
                    ports:
                        - containerPort: 9200 
                    volumeMounts:
                        -   name:   test-elasticsearch
                            mountPath:  /tmp/tests
                        -   name:   datos-aplicacion
                            mountPath:  /usr/share/elasticsearch/data
                    env:
                        -   name:   node.name # es-0 es-1, es-2
                            #value:  lucas # TODO ???? Cada replica, tiene que tener una vairable de entorno, con un valor UNICO
                            valueFrom:
                                #configMapKeyRef
                                #secretKeyRef
                                fieldRef:   
                                    fieldPath: metadata.name
                    envFrom:
                        - configMapRef:
                            name: datos-aplicacion
                    readinessProbe:
                        exec:
                            command: 
                                - /tmp/tests/ready.sh
                        initialDelaySeconds:    1
                        periodSeconds:          5
                        timeoutSeconds:         2
                        successThreshold:       1
                        failureThreshold:       3
                        
---
kind:           Service
apiVersion:     v1

metadata:
    name:       elasticsearch 

spec: 
    type:       LoadBalancer
    ports:  
               -    port: 9200 
                    targetPort: 9200
                    nodePort: 30200
    selector:
        app:    elasticsearch  